### ISSUE TITLE
2018.4.27f1 (LTS) manifest not recognised

### ISSUE THREAD

**Issue by Vivraan** [Unity-CI/Website#37]
**Describe the bug**
Unable to use 2018.4.27f1 docker image.

**To Reproduce**
Follow https://unity-ci.com/docs/github/activation up till **Acquiring an activation file**.

**Expected behavior**
Should work properly given that the docker image has been [made available by GabLeRoux today](https://gitlab.com/gableroux/unity3d/-/issues/94).

**Screenshots** / **Log**
![image](https://user-images.githubusercontent.com/12777564/94337344-5eca0100-0007-11eb-9c06-00920cb4391b.png)

```
Run webbertakken/unity-request-manual-activation-file@v1.1
/usr/bin/docker build /home/runner/work/_actions/webbertakken/unity-request-manual-activation-file/v1.1/action --file /home/runner/work/_actions/webbertakken/unity-request-manual-activation-file/v1.1/action/Dockerfile --build-arg IMAGE=gableroux/unity3d:2018.4.27f1 --tag unity-action:2018.4.27f1
Sending build context to Docker daemon  132.1kB

Step 1/12 : ARG IMAGE
Step 2/12 : FROM $IMAGE
manifest for gableroux/unity3d:2018.4.27f1 not found: manifest unknown: manifest unknown
Error: The process '/usr/bin/docker' failed with exit code 1
```

**Additional context**
The 2018.4.27f1 images were not available [until today](https://gitlab.com/gableroux/unity3d/-/issues/94). It could be an issue in the way the images are made available through his repo.

**Comment by GabLeRoux** [comment]
hi, linked issue was still open until this morning. Manifest is not found when the image doesn’t exist on docker hub and that is totally expected.

I just merged the related merge request and image will be available in around an hour.

Merge request wasn’t merged automatically because this version failed to setup an linux IL2CPP component image. that’s an upstream issue related to 2018 versions, but it has nothing to do with the unity-ci.com website repository.

Are you asking for a better output in the builder or improved documentation concerning the manifest error?

**Comment by Vivraan** [comment]
No, the manifest error was most appropriate, but I was suspecting a problem with this repo.

Glad to hear that it's not - gotta verify it still!

**Comment by Vivraan** [comment]
Verifying that the image was detected and the action occurred successfully!

Thank you all for your kind assistance and support! Closing this issue.
